name: build our image for dev

on:
  push:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag mhzawadi/picocms:dev \
            --platform linux/amd64,linux/arm64 .
